<Project Sdk="Aspire.AppHost.Sdk/13.6.0">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>70b45252-a644-49b5-b5e4-e0cb88db7279</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Dotnet" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>
</Project>