<Project Sdk="Aspire.AppHost.Sdk/13.4.6">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ChronicleOfHeros.Api/ChronicleOfHeros.Api.csproj" />
    <ProjectReference Include="../ChronicleOfHeros.Migrations/ChronicleOfHeros.Migrations.csproj" />
    <ProjectReference Include="../ChronicleOfHeros.Web/ChronicleOfHeros.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>
</Project>