<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TngTech.ArchUnitNET" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnitV3" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/ChronicleOfHeros.Api/ChronicleOfHeros.Api.csproj" />
    <ProjectReference Include="../../src/ChronicleOfHeros.AppHost/ChronicleOfHeros.AppHost.csproj" />
    <ProjectReference Include="../../src/ChronicleOfHeros.Identity.AspNetCore/ChronicleOfHeros.Identity.AspNetCore.csproj" />
    <ProjectReference Include="../../src/ChronicleOfHeros.Identity.Contracts/ChronicleOfHeros.Identity.Contracts.csproj" />
    <ProjectReference Include="../../src/ChronicleOfHeros.Migrations/ChronicleOfHeros.Migrations.csproj" />
    <ProjectReference Include="../../src/ChronicleOfHeros.ServiceDefaults/ChronicleOfHeros.ServiceDefaults.csproj" />
    <ProjectReference Include="../../src/ChronicleOfHeros.Web/ChronicleOfHeros.Web.csproj" />
    <ProjectReference Include="../../src/ChronicleOfHeros.Web.Client/ChronicleOfHeros.Web.Client.csproj" />
  </ItemGroup>
</Project>